
on:
  workflow_dispatch:

name: Update Windows
jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      # First
      - name: Checkout windows branch
        uses: actions/checkout@v3
        with:
          ref: windows
          path: windows
      # Second
      - name: Checkout linux branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
