
on:
  workflow_dispatch:

name: Update Windows
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # First
      - name: Checkout windows branch
        uses: actions/checkout@v3
        with:
          ref: windows
          path: windows
      # Second
      - name: Checkout linux branch
        uses: actions/checkout@v3
        with:
          ref: linux
          path: linux
      # Third
      - name: Checkout action branch
        uses: actions/checkout@v3
        with:
          ref: action
          path: action
      # 
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}


