
on:
  workflow_dispatch:

name: Update Windows Branch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # First
      - name: Checkout windows branch
        uses: actions/checkout@v3
        with:
          ref: windows
          path: windows
      # Second
      - name: Checkout linux branch
        uses: actions/checkout@v3
        with:
          ref: linux
          path: linux
      # Third
      - name: Checkout action branch
        uses: actions/checkout@v3
        with:
          ref: action
          path: action
      # 
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}

      - name: Run script
        shell: bash
        run: |
          chmod a+x ./action/run.sh
          ./action/run.sh
      - name: Sync from Linux-branch
        run: |
          cd ./linux
          COMMIT=`git log -n 1 --oneline | cut -d ' ' -f 1`
          cd ..
          
          cd ./windows
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Sync from Linux branch: $COMMIT"
          
      - name: Push changes to Windows-Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ./windows
          branch: windows


          


